server:
    port: 8888
spring:
    application:
        name: configuration-server
    cloud:
        config:
            server:
                git:
                    uri: /home/abbos/IdeaProjects/micro-in-action/chapter-six/config-server-resource
                    default-label: master


eureka:
    client:
        service-url:
            defaultZone: "http://localhost:8761/eureka"
