server:
    port: 8888
spring:
    application:
        name: configuration-server
    cloud:
        config:
            server:
                git:
                    uri: C:\Users\abbos\IdeaProjects\micorservices-in-action\chapter-9\microservice-app\config-server-resource
                    default-label: master


eureka:
    client:
        service-url:
            defaultZone: "http://localhost:8761/eureka"
