logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
          gateway.route.RouteDefinitionLocator: INFO
    root: info
spring:
  cloud:
    gateway:
      routes:
        -   id: service-a
            predicates:
              - Path=/api/service-a/*
            uri: lb://service-a
        -   id: service-b
            predicates:
              - Path=/api/poet/*
            uri: lb://service-b
        -   id: service-c
            predicates:
              - Path=/api/tale/*
            uri: lb://service-c
        -   filters:
              - SetPath=/
            id: discovery-service
            predicates:
              - Path=/eureka/web
            uri: http://localhost:8761
        -   id: discovery-service
            predicates:
              - Path=/eureka/**
            uri: http://localhost:8761
